code/dailyfresh/apps/cart/urls.py
from django.conf.urls import url

from apps.cart import views

urlpatterns = [
    # 添加商品到购物车
    url(r'^add$', views.AddCartView.as_view(), name='add'),
    # 更新购物车
    url(r'^update$', views.CartUpdateView.as_view(), name='update'),
    # 删除购物车数据
    url(r'^delete$', views.CartDeleteView.as_view(), name='delete'),
    # 添加商品到购物车
    url(r'^$', views.CartInfoView.as_view(), name='info'),
]

code/dailyfresh/apps/goods/urls.py
from django.conf.urls import url

from apps.goods import views

urlpatterns = [
    url('^index$', views.IndexView.as_view(), name='index'),
    # 商品详情表 127.0.0.1:8000/goods/detail/商品id
    url('^detail/(\d+)$', views.DetailView.as_view(), name='detail'),
    # 商品列表 127.0.0.1:8000/goods/list/categories_id/page_num?=default
    url('^list/(\d+)/(\d+)$', views.ListView.as_view(), name='list'),
]

code/dailyfresh/apps/users/urls.py
from django.conf.urls import url, include

from apps.users import views

urlpatterns = [
    # 注册界面 127.0.0.1:8000/users/register
    url(r'^register$', views.RegisterView.as_view(), name='register'),
    # 激活邮件
    url(r'^active/(.+)$', views.ActiveView.as_view(), name='active'),
    # 登陆页面的实现 127.0.0.1:8000/users/login
    url(r'^login$', views.LoginView.as_view(), name='login'),
    # 注销用户页面的实现 127.0.0.1:8000/users/logout
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),

    # 用户订单 127.0.0.1:8000/users/order
    url(r'^orders$', views.UserOrdersView.as_view(), name='order'),
    # 用户地址 127.0.0.1:8000/users/address
    url(r'^address$', views.UserAddressView.as_view(), name='address'),
    # 用户中心 127.0.0.1:8000/users
    url(r'^$', views.UserInfoView.as_view(), name='info')

]

code/dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^orders/', include('apps.orders.urls', namespace='orders')),

    url(r'^search/', include('haystack.urls')),

    url(r'^', include('apps.goods.urls', namespace='goods')),
]

code/dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

code/dailyfresh/apps/cart/views.py
from django.http.response import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.views.generic import View
from django_redis import get_redis_connection
from redis.client import StrictRedis

from apps.goods.models import GoodsSKU


class AddCartView(View):
    def post(self, request):
        # 判断用户是否登陆
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '用户为登陆'})
        # 获取请求数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 校验是否为空
        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'errmsg': '数据不能为空'})
        # 检验商品id是否正确
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 3, 'errmsg': '商品id不存在'})
        try:
            count = int(count)
        except:
            return JsonResponse({'code': 3, 'errmsg': '商品id不存在'})

        # cart_1 = {1:2,2:3}
        strict_redis = get_redis_connection('default')  # type: StrictRedis
        key = 'cart_%s' % request.user.id
        val = strict_redis.hget(key, sku_id)  # bytes
        if val:
            count += int(val)
        # 判断库存
        if sku.stock < count:
            return JsonResponse({'code': 4, 'errmsg': '库存不足'})
        # 设置redis数据库
        strict_redis.hset(key, sku_id, count)
        # 查询购物车中的商品总数量
        total_count = 0
        vals = strict_redis.hvals(key)  # 列表 bytes
        for val in vals:
            total_count += int(val)
        return JsonResponse({'code': 0, 'total_count': total_count})


class CartInfoView(View):
    def get(self, request):
        '''显示购物车界面'''
        # 获取登陆用户id
        user_id = request.user.id
        # 定义一个列表,保存用户购物车中的所有商品
        skus = []
        # 总数量
        total_count = 0
        # 总金额
        total_amount = 0
        # 从redis中查询出当前登陆用户的商品
        # cart_1 = {1:2, 2:3}

        strict_redis = get_redis_connection()  # type StrictRedis
        key = 'cart_%s' % user_id
        # 获取所有的键(商品id) 列表(bytes)
        sku_ids = strict_redis.hkeys(key)
        for sku_id in sku_ids:
            sku = GoodsSKU.objects.get(id=int(sku_id))  # bytes
            count = strict_redis.hget(key, sku_id)  # bytes
            amount = sku.price * int(count)
            # 给商品对象新增实例属性, 数量小计金额amount
            sku.count = int(count)
            sku.amount = amount
            # 累计总数量和总金额
            total_count += int(count)
            total_amount += amount
            skus.append(sku)
        # 定义模板数据
        context = {
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount,
        }
        return render(request, 'cart.html', context)


class CartUpdateView(View):
    def post(self, request):
        '''修改商品数量'''
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请先登陆'})
        # 获取参数 sku_id, count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 校验参数合法性
        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'errmsg': '参数不能为空'})
        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 3, 'errmsg': '商品不存在'})
        # 判断是否为整数
        try:
            count = int(count)
        except:
            return JsonResponse({'code': 3, 'errmsg': 'count需为整数'})
        # 判断库存
        if count > sku.stock:
            return JsonResponse({'code': 4, 'errmsg': '库存不足'})
        # 如果用户登陆将修改redis数据
        strict_redis = get_redis_connection()  # type: StrictRedis
        key = 'cart_%s' % request.user.id
        strict_redis.hset(key, sku_id, count)
        # 查询购物车中的商品总数量
        total_count = 0
        vals = strict_redis.hvals(key)
        for val in vals:
            total_count += int(val)
        return JsonResponse({'code': 0, 'total_count': total_count})


class CartDeleteView(View):
    pass

code/dailyfresh/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block top_js %}
    {% endblock %}
</head>
<body>

{% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'users:logout' %}">注销</a>

                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'users:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'users:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'users:info' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:info' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'users:order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block seach_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <form method="get" action="/search">
            <div class="search_con fl">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </div>
        </form>

        <div class="guest_cart fr">
            <a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock %}
{% block body %}
{% endblock %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>


{% block bottom_js %}

{% endblock %}
</body>
</html>

code/dailyfresh/templates/base_nocaet.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block seach_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock %}</div>
        <form method="get" action="/search">
            <div class="search_con fl">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </div>
        </form>
    </div>
{% endblock %}

code/dailyfresh/templates/detail.html
{% extends 'base.html' %}
{% block title %}
    天天生鲜-商品详情
{% endblock %}

{% block body %}

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in categories %}
                        <li><a href="{% url 'goods:list' category.id 1 %}?sort=default"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ sku.category.name }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.title }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unit }}</span>
                <span class="show_stock">库  存：{{ sku.stock }}</span>
            </div>
            {% if other_skus %}
                <div>
                    <p>其他规格的商品:</p>
                    <ul>
                        {% for sku in other_skus %}
                            <a href="{% url 'goods:detail' sku.id %}">
                                <li>{{ sku.name }}</li>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}


            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>
                </div>
            </div>
            <div class="total">总价：<em>16.80元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" sku_id="{{ sku.id }}" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for news_sku in news_skus %}
                        <li>
                            <a href="{% url 'goods:detail' news_sku.id %} "><img src="{{ news_sku.default_image.url }}"></a>
                            <h4><a href="#">{{ news_sku.name }}</a></h4>
                            <div class="prize">￥{{ news_sku.price }}</div>
                        </li>
                    {% endfor %}


                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ sku.spu.desc|safe }}
                    </dd>
                </dl>
            </div>

        </div>
    </div>
{% endblock %}
{% block bottom_js %}
    {% load staticfiles %}
    {% csrf_token %}
    <div class="add_jump"></div>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        update_goods_info();

        // 更新商品总金额
        function update_goods_info() {
            // 获取商品数量和价格
            var count = $('.num_show').val();
            var price = $('.show_pirze').children('em').text();
            // 转换类型
            count = parseInt(count);
            price = parseFloat(price);
            // 显示总金额 toFixed: 保留两位小数点
            var amount = count * price;
            $('.total').children('em').html(amount.toFixed(2) + '元')

        }

        // 点击加号新增商品数量
        $('.add').click(function () {
            // 获取当前商品数量
            var count = $('.num_show').val();
            count = parseInt(count);
            // 数量加1
            count += 1;
            //更新数量显示
            $('.num_show').val(count);
            update_goods_info();
        });
        // 点击减号新增商品数量
        $('.minus').click(function () {
            // 获取当前商品数量
            var count = $('.num_show').val();
            count = parseInt(count);
            if (count > 1) {
                count -= 1;
                // 更新数量显示
                $('.num_show').val(count);
                update_goods_info();
            }
        });
        // 手动输入商品数量
        // blur 监听失去焦点
        $('.num_show').blur(function () {
            // 获取当前商品数量
            var count = $('.num_show').val();
            //判断内容合法性: 非数字,空字符串,负数
            if (isNaN(count) || count.trim().length == 0 || parseInt(count) < 1) {
                // 不合法 重置为1
                count = 1;
            }
            // 显示数量
            $('.num_show').val(parseInt(count));
            update_goods_info();
        });
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;
        // 添加商品到购物车
        $('.add_cart').click(function () {
            $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'});

            // 获取商品数量和商品id
            var count = $('.num_show').val();
            var sku_id = $(this).attr('sku_id');
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            // 定义post请求参数(js对象)
            var params = {
                sku_id: sku_id,
                count: count,
                csrfmiddlewaretoken: csrf

            };
            // 通过ajax发起post请求
            // 参数1: 请求url路径
            $.post('/cart/add', params, function (data) {
                // data: 返回请求结果
                //{'code':0,'total_count':4}
                //{'code':0,库存不足}
                if (data.code == 0) {
                    // 请求成功, 执行移动的动画效果
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                var total_count = data.total_count;
                                $('#show_count').html(total_count);
                            });
                        });
                } else {
                    // 请求失败 (添加商品到购物车失败)
                    alert(data.errmsg)
                }
            })
        });
    </script>
{% endblock %}
	

code/dailyfresh/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    天天生鲜-首页
{% endblock %}
{% block top_js %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for category in categories %}
                <li><a href="#model0{{ forloop.counter }}"
                       class="{{ category.logo }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                {% for slide_sku in slide_skus %}
                    <a href="{% url 'goods:detail' slide_sku.sku.id %}">                    <li><img src="{{ slide_sku.image.url }}" alt="幻灯片"></li>
</a>
                {% endfor %}
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for promotion in promotions %}
                <a href="#"><img src="{{ promotion.image.url }}"></a>
            {% endfor %}


        </div>
    </div>
    {% for category in categories %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model01">{{ category.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for c_sku in category.text_sku %}
                        <a href="{% url 'goods:detail' c_sku.sku.id %}">{{ c_sku.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="{% url 'goods:list' category.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ category.image.url }}"></div>
                <ul class="goods_list fl">
                    {% for i_sku in category.image_sku %}
                        <li>
                            <h4><a href="{% url 'goods:detail' i_sku.sku.id %}">{{ i_sku.sku.name }}</a></h4>
                            <a href="{% url 'goods:detail' i_sku.sku.id %}"><img src="{{ i_sku.sku.default_image.url }}"></a>
                            <div class="prize">¥ {{ i_sku.sku.price }}</div>
                        </li>
                    {% endfor %}


                </ul>
            </div>
        </div>
    {% endfor %}
{% endblock %}
{% block bottom_js %}
    <script type="text/javascript" src="js/slideshow.js"></script>
    <script type="text/javascript">
{#        BCSlideshow('focuspic');#}
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>
{% endblock %}

code/dailyfresh/templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
  天天生鲜-商品列表
{% endblock %}
{% block body %}
    <body>
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for category in categories %}
                        <li><a href="{% url 'goods:list' category.id 1 %}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' category.id 1 %}">{{ category.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_sku in new_skus %}
                        <li>
						<a href="{% url 'goods:detail' new_sku.id %}">
                            <img src="{{ new_sku.default_image.url }}"></a>
						<h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
						<div class="prize">￥{{ new_sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' category.id 1 %}?sort=default"
                   {% if sort == 'default' %}class="active" {% endif %}>默认</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=price"
                {% if sort == 'price' %}class="active" {% endif %}>价格</a>

				<a href="{% url 'goods:list' category.id 1 %}?sort=hot"
                {% if sort == 'hot' %}class="active" {% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for foo in page %}
                    <li>
					<a href="{% url 'goods:detail' foo.id %}"><img src="{{ foo.default_image.url }}"></a>
					<h4><a href="{% url 'goods:detail' foo.id %}">{{ foo.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ foo.price }}</span>
						<span class="unit">{{ foo.price }}/{{ foo.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}



			</ul>

			<div class="pagenation">
                {% if page.has_previous %}
				    <a href="{% url 'goods:list' category.id page.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for index in page_range %}
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}"
                       {% if index == page.number %}class="active" {% endif %}>{{ index }}</a>
                {% endfor %}
                {% if page.has_next %}
				    <a href="{% url 'goods:list' category.id page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>


</body>
{% endblock %}

code/dailyfresh/templates/login.html
{% load staticfiles %}
 {% csrf_token %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-登录</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="login_top clearfix">
    <a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
</div>

<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">日夜兼程 · 急速送达</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="#">立即注册</a>
            </div>
            <div class="form_input">
                <form method="post">
                   {% csrf_token %}
                    <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" name="password" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <div style="color: red">{{ revmsg }}</div>
                        <input type="checkbox" name="remember">
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <input type="submit" name="" value="登录" class="input_submit">
                </form>
            </div>
        </div>
    </div>
</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>

code/dailyfresh/templates/user_center_base.html
{% extends 'base_nocaet.html' %}
{% load staticfiles %}
{% block page_title %}
    用户中心
{% endblock %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'users:info' %}" {% if  which_page == 3 %}class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'users:order' %}" {% if  which_page == 1 %}class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'users:address' %}" {% if  which_page == 2 %}class="active"{% endif %}>· 收货地址</a></li>
            </ul>

        </div>
        {% block right %}
        {% endblock %}
    </div>
{% endblock %}

code/dailyfresh/templates/user_center_info.html
{% extends 'user_center_base.html' %}
{% load staticfiles %}
{% block right %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user }}</li>
                <li><span>联系方式：</span>{{ address.receiver_mobile }}</li>
                <li><span>联系地址：</span>{{ address.detail_addr }}</li>
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for sku in skus %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.id }}.{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}